/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EthangButton {
        "buttonProperties"?: Record<string, unknown>;
        "styleType"?: string;
    }
    interface EthangSideDrawer {
        "drawerTitle": string;
        "open": boolean;
        "toggle": () => Promise<void>;
    }
    interface EthangSpinner {
    }
    interface EthangStockFinder {
    }
    interface EthangStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLEthangButtonElement extends Components.EthangButton, HTMLStencilElement {
    }
    var HTMLEthangButtonElement: {
        prototype: HTMLEthangButtonElement;
        new (): HTMLEthangButtonElement;
    };
    interface HTMLEthangSideDrawerElement extends Components.EthangSideDrawer, HTMLStencilElement {
    }
    var HTMLEthangSideDrawerElement: {
        prototype: HTMLEthangSideDrawerElement;
        new (): HTMLEthangSideDrawerElement;
    };
    interface HTMLEthangSpinnerElement extends Components.EthangSpinner, HTMLStencilElement {
    }
    var HTMLEthangSpinnerElement: {
        prototype: HTMLEthangSpinnerElement;
        new (): HTMLEthangSpinnerElement;
    };
    interface HTMLEthangStockFinderElement extends Components.EthangStockFinder, HTMLStencilElement {
    }
    var HTMLEthangStockFinderElement: {
        prototype: HTMLEthangStockFinderElement;
        new (): HTMLEthangStockFinderElement;
    };
    interface HTMLEthangStockPriceElement extends Components.EthangStockPrice, HTMLStencilElement {
    }
    var HTMLEthangStockPriceElement: {
        prototype: HTMLEthangStockPriceElement;
        new (): HTMLEthangStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "ethang-button": HTMLEthangButtonElement;
        "ethang-side-drawer": HTMLEthangSideDrawerElement;
        "ethang-spinner": HTMLEthangSpinnerElement;
        "ethang-stock-finder": HTMLEthangStockFinderElement;
        "ethang-stock-price": HTMLEthangStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface EthangButton {
        "buttonProperties"?: Record<string, unknown>;
        "styleType"?: string;
    }
    interface EthangSideDrawer {
        "drawerTitle"?: string;
        "open"?: boolean;
    }
    interface EthangSpinner {
    }
    interface EthangStockFinder {
        "onEgSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface EthangStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "ethang-button": EthangButton;
        "ethang-side-drawer": EthangSideDrawer;
        "ethang-spinner": EthangSpinner;
        "ethang-stock-finder": EthangStockFinder;
        "ethang-stock-price": EthangStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ethang-button": LocalJSX.EthangButton & JSXBase.HTMLAttributes<HTMLEthangButtonElement>;
            "ethang-side-drawer": LocalJSX.EthangSideDrawer & JSXBase.HTMLAttributes<HTMLEthangSideDrawerElement>;
            "ethang-spinner": LocalJSX.EthangSpinner & JSXBase.HTMLAttributes<HTMLEthangSpinnerElement>;
            "ethang-stock-finder": LocalJSX.EthangStockFinder & JSXBase.HTMLAttributes<HTMLEthangStockFinderElement>;
            "ethang-stock-price": LocalJSX.EthangStockPrice & JSXBase.HTMLAttributes<HTMLEthangStockPriceElement>;
        }
    }
}
