/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EthangSideDrawer {
        "open": boolean;
        "title": string;
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLEthangSideDrawerElement extends Components.EthangSideDrawer, HTMLStencilElement {
    }
    var HTMLEthangSideDrawerElement: {
        prototype: HTMLEthangSideDrawerElement;
        new (): HTMLEthangSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ethang-side-drawer": HTMLEthangSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface EthangSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "ethang-side-drawer": EthangSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ethang-side-drawer": LocalJSX.EthangSideDrawer & JSXBase.HTMLAttributes<HTMLEthangSideDrawerElement>;
        }
    }
}
