/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EthangButton {
        "buttonProperties"?: Record<string, unknown>;
        "styleType"?: string;
    }
    interface EthangPublishUpdateTimes {
        "published": string;
        "updated": string;
    }
}
declare global {
    interface HTMLEthangButtonElement extends Components.EthangButton, HTMLStencilElement {
    }
    var HTMLEthangButtonElement: {
        prototype: HTMLEthangButtonElement;
        new (): HTMLEthangButtonElement;
    };
    interface HTMLEthangPublishUpdateTimesElement extends Components.EthangPublishUpdateTimes, HTMLStencilElement {
    }
    var HTMLEthangPublishUpdateTimesElement: {
        prototype: HTMLEthangPublishUpdateTimesElement;
        new (): HTMLEthangPublishUpdateTimesElement;
    };
    interface HTMLElementTagNameMap {
        "ethang-button": HTMLEthangButtonElement;
        "ethang-publish-update-times": HTMLEthangPublishUpdateTimesElement;
    }
}
declare namespace LocalJSX {
    interface EthangButton {
        "buttonProperties"?: Record<string, unknown>;
        "styleType"?: string;
    }
    interface EthangPublishUpdateTimes {
        "published"?: string;
        "updated"?: string;
    }
    interface IntrinsicElements {
        "ethang-button": EthangButton;
        "ethang-publish-update-times": EthangPublishUpdateTimes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ethang-button": LocalJSX.EthangButton & JSXBase.HTMLAttributes<HTMLEthangButtonElement>;
            "ethang-publish-update-times": LocalJSX.EthangPublishUpdateTimes & JSXBase.HTMLAttributes<HTMLEthangPublishUpdateTimesElement>;
        }
    }
}
