POST {{CAR_VALUE_HOST_URL}}/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1980,
  "mileage": 100000,
  "saleLongitude": 0,
  "saleLatitude": 0,
  "price": 500000
}
