name: "EthanG CI"

on:
  push:
    branches: [ develop ]
  schedule:
    - cron: '43 21 * * 3'

jobs:
  browsersUpdate:
    name: Browsers Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache PNPM Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.11.0
          run_install: true
      - name: Update Browsers List
        run: pnpm browserslist --update-db
      - name: Commit Changes
        continue-on-error: true
        run: |
          git config --global user.name 'eglove'
          git config --global user.email 'eglove@users.noreaply.github.com'
          git commit -am 'Browsers Update'
          git push

  codeQl:
    needs: [ browsersUpdate ]
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  snykNode:
    needs: [ browsersUpdate ]
    name: Snyk Node Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.11.0
          run_install: true
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low

  sonar:
    needs: [ browsersUpdate ]
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
