name: "EthanG CI"

on:
  push:
    branches: [ develop ]
  schedule:
    - cron: '43 21 * * 3'

jobs:
  browsersUpdate:
    name: Browsers Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache PNPM Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.11.0
          run_install: true
      - name: Update Browsers List
        run: pnpm browserslist --update-db
      - name: Commit Changes
        continue-on-error: true
        run: |
          git config --global user.name 'eglove'
          git config --global user.email 'eglove@users.noreaply.github.com'
          git commit -am 'Browsers Update'
          git push

  codeQl:
    needs: [ browsersUpdate ]
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  snykNode:
    needs: [ browsersUpdate ]
    name: Snyk Node Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.11.0
          run_install: true
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low

  sonar:
    needs: [ browsersUpdate ]
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  nxMain:
    runs-on: ubuntu-latest
    needs: [ codeQl, snykNode, sonar ]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          uses: nrwl/nx-set-shas@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '17'
        - run: npm install
        - run: npx nx-cloud start-ci-run
        - run: npx nx affected --target=build --parallel --max-parallel=3
        - run: npx nx affected --target=test --parallel --max-parallel=2
        - run: npx nx-cloud stop-all-agents

  nxPr:
    runs-on: ubuntu-latest
    needs: [ codeQl, snykNode, sonar ]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx nx affected --target=test --parallel --max-parallel=2
      - run: npx nx-cloud stop-all-agents

  nxAgents:
    runs-on: ubuntu-latest
    needs: [ codeQl, snykNode, sonar ]
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  mainMerge:
    name: Merge to Main
    needs: [ codeQl, snykNode, sonar ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to Main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}
